name: Event Demo 1
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  test: 
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: flutter pub get



    