name: Event Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
  workflow_dispatch:
  push:
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test: 
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Get dependencies
        run: flutter pub get
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          dry-run: true
      - run: |
         echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
         echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
         echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
         echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
         echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
         echo PUB-CACHE-PATH=${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}
         echo PUB-CACHE-KEY=${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}
        shell: bash
      - name: Build APK
        run: flutter build apk
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with: 
          name: my-apk
          path: build
  deploy: 
    needs: build
    runs-on: macos-latest
    steps: 
      - name: Download apk
        uses: actions/download-artifact@v4
        with: 
          name: my-apk
      - name: Download path
        run: ls
        
        



    