name: Event Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
  workflow_dispatch:
  push:
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test: 
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Run test
        run: flutter test
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with: 
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Decode keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE_BASE_64 }}
        run: echo $KEYSTORE | base64 --decode > /tmp/keystore.jks
      - name: Set up key.properties
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "keyPassword=${{ secrets.KEY_STORE }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "storeFile=/tmp/keystore.jks" >> $GITHUB_WORKSPACE/android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
        



    