name: Event Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
  workflow_dispatch:
  push:
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test: 
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Run test
        run: flutter test
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with: 
          channel: stable
      - name: Get dependencies
        run: flutter pub get

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE_64 }}
          DECODED_KEYSTORE_PATH: /path/to/keystore.jks
        run: |
          echo $ENCODED_KEYSTORE > keystore-b64.txt
          base64 -d keystore-b64.txt > $DECODED_KEYSTORE_PATH

      - name: Build Release apk
        env:
            RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEY_STORE_PASSWORD }}
            RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
            RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease --stacktrace
    
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
        



    