name: Event Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
  workflow_dispatch:
  push:
    branches:
      - master # main  
      - 'dev-*' # dev-new dev-new-1
      - 'feature/**' # feature/new feature/new/new1
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test: 
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Get dependencies
        run: flutter pub get
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"  
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Get dependencies
        run: flutter pub get
        
        



    